### ISSUE TITLE
Add support for location

### ISSUE THREAD

**Issue by s-sebastian** [saltstack-formulas/resolver-formula#14]
Hi,

I would like to push a different nameservers based on physical location. I've got a working example but as far as I know it's not recommended to place Jinja code into state files therefore could you please advise what's the best approach to solve this?

```
# diff -u init.sls{.orig,}
--- init.sls.orig	2015-07-23 23:19:13.840496937 +0100
+++ init.sls	2015-07-23 23:20:50.349496937 +0100
@@ -11,6 +11,10 @@
     - source: salt://formulas/resolver/files/resolv.conf
     - template: jinja
     - defaults:
-        nameservers: {{ salt['pillar.get']('resolver:nameservers', ['8.8.8.8','8.8.4.4']) }}
+        {% if grains['location'] == 'gb' %}
+        nameservers: {{ salt['pillar.get']('resolver:nameservers_gb', ['8.8.8.8','8.8.4.4']) }}
+        {% elif grains['location'] == 'us' %}
+        nameservers: {{ salt['pillar.get']('resolver:nameservers_us', ['8.8.8.8','8.8.4.4']) }}
+        {% endif %}
         searchpaths: {{ salt['pillar.get']('resolver:searchpaths', [salt['grains.get']('domain'),]) }}
         options: {{ salt['pillar.get']('resolver:options', []) }}
```

Pillar.example:
```
resolver:
  searchpaths:
    - exmaple.com
  nameservers_gb:
    - 1.1.1.1
    - 2.2.2.2
  nameservers_us:
    - 3.3.3.3
    - 4.4.4.4
  options:
    - 'rotate'
```
